export interface ThemeColors {
  id: string;
  name: string;
  header: string;
  headerDivider: string;
  panel1Bg: string;
  panel1Header: string;
  panel1ContentBg: string;
  inputBg: string;
  inputBorder: string;
  buttonPrimary: string;
  buttonPrimaryHover: string;
  buttonBorder: string;
  textPrimary: string;
  textSecondary: string;
  accentColor: string;
}

export const themes: Record<string, ThemeColors> = {
  "default": {
    id: "default",
    name: "Default",
    header: "bg-gray-800",
    headerDivider: "bg-gray-400",
    panel1Bg: "bg-blue-500",
    panel1Header: "border-pink-500",
    panel1ContentBg: "bg-gray-900",
    inputBg: "bg-slate-800",
    inputBorder: "border-slate-700",
    buttonPrimary: "bg-blue-600",
    buttonPrimaryHover: "hover:bg-blue-700",
    buttonBorder: "border-blue-500",
    textPrimary: "text-white",
    textSecondary: "text-gray-400",
    accentColor: "bg-pink-500"
  },
  "dark": {
    id: "dark",
    name: "Dark",
    header: "bg-black",
    headerDivider: "bg-gray-600",
    panel1Bg: "bg-gray-800",
    panel1Header: "border-gray-600",
    panel1ContentBg: "bg-black",
    inputBg: "bg-gray-900",
    inputBorder: "border-gray-800",
    buttonPrimary: "bg-gray-700",
    buttonPrimaryHover: "hover:bg-gray-600",
    buttonBorder: "border-gray-600",
    textPrimary: "text-white",
    textSecondary: "text-gray-500",
    accentColor: "bg-gray-600"
  },
  "modern-dark": {
    id: "modern-dark",
    name: "Modern Dark",
    header: "bg-gray-800",
    headerDivider: "bg-gray-400",
    panel1Bg: "bg-blue-500",
    panel1Header: "border-pink-500",
    panel1ContentBg: "bg-gray-900",
    inputBg: "bg-slate-800",
    inputBorder: "border-slate-700",
    buttonPrimary: "bg-blue-600",
    buttonPrimaryHover: "hover:bg-blue-700",
    buttonBorder: "border-blue-500",
    textPrimary: "text-white",
    textSecondary: "text-gray-400",
    accentColor: "bg-pink-500"
  },
  "midnight-blue": {
    id: "midnight-blue",
    name: "Midnight Blue",
    header: "bg-slate-900",
    headerDivider: "bg-blue-500",
    panel1Bg: "bg-blue-900",
    panel1Header: "border-cyan-500",
    panel1ContentBg: "bg-slate-950",
    inputBg: "bg-blue-950",
    inputBorder: "border-blue-900",
    buttonPrimary: "bg-cyan-700",
    buttonPrimaryHover: "hover:bg-cyan-600",
    buttonBorder: "border-cyan-500",
    textPrimary: "text-white",
    textSecondary: "text-cyan-300",
    accentColor: "bg-cyan-500"
  },
  "dusk": {
    id: "dusk",
    name: "Dusk",
    header: "bg-stone-900",
    headerDivider: "bg-amber-600",
    panel1Bg: "bg-amber-900",
    panel1Header: "border-amber-600",
    panel1ContentBg: "bg-stone-950",
    inputBg: "bg-stone-900",
    inputBorder: "border-stone-800",
    buttonPrimary: "bg-amber-700",
    buttonPrimaryHover: "hover:bg-amber-600",
    buttonBorder: "border-amber-600",
    textPrimary: "text-white",
    textSecondary: "text-amber-300",
    accentColor: "bg-amber-500"
  },
  "sunset": {
    id: "sunset",
    name: "Sunset",
    header: "bg-purple-900",
    headerDivider: "bg-pink-500",
    panel1Bg: "bg-purple-700",
    panel1Header: "border-pink-500",
    panel1ContentBg: "bg-purple-950",
    inputBg: "bg-purple-900",
    inputBorder: "border-purple-800",
    buttonPrimary: "bg-pink-700",
    buttonPrimaryHover: "hover:bg-pink-600",
    buttonBorder: "border-pink-500",
    textPrimary: "text-white",
    textSecondary: "text-pink-300",
    accentColor: "bg-pink-500"
  },
  "purple": {
    id: "purple",
    name: "Purple",
    header: "bg-purple-900",
    headerDivider: "bg-purple-500",
    panel1Bg: "bg-purple-700",
    panel1Header: "border-purple-500",
    panel1ContentBg: "bg-purple-950",
    inputBg: "bg-purple-900",
    inputBorder: "border-purple-800",
    buttonPrimary: "bg-purple-600",
    buttonPrimaryHover: "hover:bg-purple-500",
    buttonBorder: "border-purple-500",
    textPrimary: "text-white",
    textSecondary: "text-purple-300",
    accentColor: "bg-purple-500"
  },
  "forest": {
    id: "forest",
    name: "Forest",
    header: "bg-green-950",
    headerDivider: "bg-green-500",
    panel1Bg: "bg-green-800",
    panel1Header: "border-green-500",
    panel1ContentBg: "bg-emerald-950",
    inputBg: "bg-green-950",
    inputBorder: "border-green-900",
    buttonPrimary: "bg-green-700",
    buttonPrimaryHover: "hover:bg-green-600",
    buttonBorder: "border-green-500",
    textPrimary: "text-white",
    textSecondary: "text-green-300",
    accentColor: "bg-green-500"
  },
  "crimson": {
    id: "crimson",
    name: "Crimson",
    header: "bg-red-950",
    headerDivider: "bg-red-500",
    panel1Bg: "bg-red-800",
    panel1Header: "border-red-500",
    panel1ContentBg: "bg-rose-950",
    inputBg: "bg-red-950",
    inputBorder: "border-red-900",
    buttonPrimary: "bg-red-700",
    buttonPrimaryHover: "hover:bg-red-600",
    buttonBorder: "border-red-500",
    textPrimary: "text-white",
    textSecondary: "text-red-300",
    accentColor: "bg-red-500"
  },
  "cyan": {
    id: "cyan",
    name: "Cyan",
    header: "bg-slate-900",
    headerDivider: "bg-cyan-500",
    panel1Bg: "bg-cyan-700",
    panel1Header: "border-cyan-500",
    panel1ContentBg: "bg-slate-950",
    inputBg: "bg-cyan-950",
    inputBorder: "border-cyan-900",
    buttonPrimary: "bg-cyan-700",
    buttonPrimaryHover: "hover:bg-cyan-600",
    buttonBorder: "border-cyan-500",
    textPrimary: "text-white",
    textSecondary: "text-cyan-300",
    accentColor: "bg-cyan-400"
  },
  "gold": {
    id: "gold",
    name: "Gold",
    header: "bg-yellow-950",
    headerDivider: "bg-yellow-500",
    panel1Bg: "bg-yellow-700",
    panel1Header: "border-yellow-500",
    panel1ContentBg: "bg-amber-950",
    inputBg: "bg-yellow-950",
    inputBorder: "border-yellow-900",
    buttonPrimary: "bg-yellow-700",
    buttonPrimaryHover: "hover:bg-yellow-600",
    buttonBorder: "border-yellow-500",
    textPrimary: "text-white",
    textSecondary: "text-yellow-300",
    accentColor: "bg-yellow-500"
  },
  "orange": {
    id: "orange",
    name: "Orange",
    header: "bg-orange-950",
    headerDivider: "bg-orange-500",
    panel1Bg: "bg-orange-700",
    panel1Header: "border-orange-500",
    panel1ContentBg: "bg-red-950",
    inputBg: "bg-orange-950",
    inputBorder: "border-orange-900",
    buttonPrimary: "bg-orange-700",
    buttonPrimaryHover: "hover:bg-orange-600",
    buttonBorder: "border-orange-500",
    textPrimary: "text-white",
    textSecondary: "text-orange-300",
    accentColor: "bg-orange-500"
  },
  "pink": {
    id: "pink",
    name: "Pink",
    header: "bg-pink-950",
    headerDivider: "bg-pink-500",
    panel1Bg: "bg-pink-700",
    panel1Header: "border-pink-500",
    panel1ContentBg: "bg-fuchsia-950",
    inputBg: "bg-pink-950",
    inputBorder: "border-pink-900",
    buttonPrimary: "bg-pink-700",
    buttonPrimaryHover: "hover:bg-pink-600",
    buttonBorder: "border-pink-500",
    textPrimary: "text-white",
    textSecondary: "text-pink-300",
    accentColor: "bg-pink-500"
  },
  "mint": {
    id: "mint",
    name: "Mint",
    header: "bg-emerald-950",
    headerDivider: "bg-emerald-500",
    panel1Bg: "bg-emerald-700",
    panel1Header: "border-emerald-500",
    panel1ContentBg: "bg-teal-950",
    inputBg: "bg-emerald-950",
    inputBorder: "border-emerald-900",
    buttonPrimary: "bg-emerald-700",
    buttonPrimaryHover: "hover:bg-emerald-600",
    buttonBorder: "border-emerald-500",
    textPrimary: "text-white",
    textSecondary: "text-emerald-300",
    accentColor: "bg-emerald-400"
  },
  "lavender": {
    id: "lavender",
    name: "Lavender",
    header: "bg-violet-950",
    headerDivider: "bg-violet-500",
    panel1Bg: "bg-violet-700",
    panel1Header: "border-violet-500",
    panel1ContentBg: "bg-purple-950",
    inputBg: "bg-violet-950",
    inputBorder: "border-violet-900",
    buttonPrimary: "bg-violet-700",
    buttonPrimaryHover: "hover:bg-violet-600",
    buttonBorder: "border-violet-500",
    textPrimary: "text-white",
    textSecondary: "text-violet-300",
    accentColor: "bg-violet-400"
  }
};

export function getTheme(themeId: string): ThemeColors {
  return themes[themeId] || themes["modern-dark"];
}
